# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EC2Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('active', models.BooleanField(default=True)),
                ('last_update_time', models.DateTimeField()),
                ('name', models.CharField(max_length=500)),
                ('instance_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
                ('private_ip_address', models.CharField(max_length=500)),
                ('key_pair', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EventHandleRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(db_index=True, max_length=500)),
                ('event_type', models.CharField(max_length=500)),
                ('handler', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('action', models.CharField(max_length=500)),
                ('result', models.CharField(max_length=100)),
                ('args', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('version', models.CharField(max_length=500)),
                ('launch_config', models.TextField()),
                ('service_type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=500)),
                ('resource_type', models.CharField(max_length=500)),
                ('event_type', models.CharField(max_length=500)),
                ('resource_id', models.CharField(max_length=500)),
                ('event_state', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('result_detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=500)),
                ('profile_name', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='onlineevent',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asset.Region'),
        ),
        migrations.AddField(
            model_name='module',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Region'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.OnlineEvent'),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Module'),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Region'),
        ),
    ]
