# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHandleRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(db_index=True, max_length=500)),
                ('event_type', models.CharField(max_length=500)),
                ('handler', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('action', models.CharField(max_length=500)),
                ('result', models.CharField(max_length=100)),
                ('args', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OnlineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=500)),
                ('resource_type', models.CharField(max_length=500)),
                ('event_type', models.CharField(max_length=500)),
                ('resource_id', models.CharField(max_length=500)),
                ('event_state', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('result_detail', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='eventlog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.OnlineEvent'),
        ),
    ]
