# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_module_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRepairSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_repair', models.BooleanField()),
            ],
        ),
    ]
