# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20170612_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='profile_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
