# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_autorepairswitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGroupIsolated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpc_id', models.CharField(db_index=True, max_length=200)),
                ('group_name', models.CharField(max_length=200)),
                ('group_id', models.CharField(max_length=200)),
            ],
        ),
    ]
