# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_onlineevent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineevent',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asset.Region'),
        ),
    ]
