# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_securitygroupisolated'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitygroupisolated',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
