# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_onlineevent_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineevent',
            old_name='module',
            new_name='region',
        ),
    ]
