# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20170707_1527'),
        ('asset', '0005_securitygroupisolated_note'),
    ]

    operations = [
    ]
