# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_merge_20171017_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
