# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_ec2instance_last_checked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ec2instance',
            name='last_update_time',
        ),
    ]
