# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-20 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_remove_ec2instance_last_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
